### ISSUE TITLE
First Mission: Contributors Page

### ISSUE THREAD

**Issue by coni2k** [forCrowd/WealthEconomy#82]
[UPDATE] Backbone is our active project at the moment, to continue to "First Mission", please visit:
https://github.com/forCrowd/Backbone/issues/13

Project links:
https://backbone.forcrowd.org
https://github.com/forCrowd/Backbone/

---

This is an experimental attempt to help you to get familiar with our project and make your first pull request.

Follow this tutorial on our wiki to get started:
https://github.com/forCrowd/WealthEconomy/wiki/First-Mission

**Comment by TheOnlyRealTodd** [comment]
Hello. How is this project going? I want to get on it! I am an ASP.NET MVC/Web API Jr. Dev looking to get on a project like this. I'll pull it down and add myself in shortly. I'm seeing last changes as months ago, is the project still alive?

**Comment by coni2k** [comment]
Hi TheOnlyRealTodd,
Thanks for your interest in the project.
Yes, hopefully the project will be alive till I can make something out of it. My current item is to upgrade front-end part to Angular2. That takes some time, plus I'm on a trip at the moment. I will be back to full-time work around two weeks.

I have lot of plans for the project, big and small, however mostly I wrote as my personal notes. So, if you have something specific on your mind about the project, let me know. Otherwise I can try to find something suitable for you?

**Comment by TheOnlyRealTodd** [comment]
@coni2k great yeah that sounds good. I read over the instructions to add myself and will probably do that tomorrow when I have some time. I do not know Angular2 yet, but I do have experience with MVC/Web API/Entity Framework.

**Comment by coni2k** [comment]
Sure, please try to add your name to the list, so you can see whether the project runs on your computer without any issues.

Angular is not a necessity, your backend knowledge totally fits.

I'm hoping to achieve, initially, an embeddable (to other websites) dynamic survey/simulator kind of application, by retrieving and saving the data through WebApi.

After angular2, I'd like to focus on Asp.Net Core by the way, did you have time to look at that?

**Comment by TheOnlyRealTodd** [comment]
@coni2k I have looked at .NET Core. I have not really "tackled" it yet though, as I was trying to get more experience with the previous version just so that I didn't confuse myself... However, I do get the gist of it plus I have a Pluralsight account where they have several courses on it which are beneficial.

Seems to be a lot more modular which could make for a better development experience. One thing I was experimenting with too was setting up Role and Claims-based authentication with OAuth, which was no easy task, lol. Ok I'm going to get started right now.

**Comment by TheOnlyRealTodd** [comment]
Alright so I got it on my machine and I can add myself and modify the files no big deal, but I can't get it to run because it's basically saying there is no start point. It is saying "A project of type Class Library cannot be started directly" which is obvious, but please excuse my ignorance. I tried to start the nGClient project.

**Comment by coni2k** [comment]
No problem, in Getting Started, check step 8 - in your solution, you need to tell to start both of the projects at the same time;
https://github.com/forCrowd/WealthEconomy/wiki/Getting-Started

This is one of the things that I'd like to get rid of, but Visual Studio doesn't save this setting on the project level, but keeps it on the user level, so everyone has to do this himself, bummer!

**Comment by TheOnlyRealTodd** [comment]
@coni2k ahhhh. awesome, got the servers running! This is helpful to know, in the past I just manually started them all up.

**Comment by coni2k** [comment]
Good to hear that the instructions help you :) Did you manage to handle the rest?

**Comment by TheOnlyRealTodd** [comment]
@coni2k yup! Just sent in the Pull Request finally.

**Comment by coni2k** [comment]
Todd hi,

Yep, I saw it, it's merged and published :)
https://wealth.forcrowd.org/_system/content/contributors

If you would like to update your info later on, feel free to send me a new request.

Again, thanks for your interest in the project and if you see some other parts that you can contribute, let me know, I'd happy to discuss.

**Comment by angelfeliz** [comment]
Hello i am in to contribute to this project, i liked the stack you are using to build up the project and also the economy context of the project. I did all the step to make the first pull request and is only expecting the approve. So looking forward to keep coding 👍

**Comment by coni2k** [comment]
Angel hi,
Thank you for your interest in the project, also that you mention economy context, it's good to hear.
I will try to merge your PR tonight. And afterwards we can discuss how to continue.

**Comment by shilpavijay** [comment]
Thanks. This helps!

**Comment by nakanoer** [comment]
I really appreciated this First Mission, as I am very new to coding and open source projects. I am currently taking a class in open source, which is why I ended up looking for something to contribute to in the first place. You really made my first pull request very easy and unintimidating. I had a couple of hiccups along the way, but looking back, it's probably because I really don't know enough about the programming world just yet and also because I have never used Visual Studio and Node.

The instructions for both the "Getting Started" page as well as the "First Mission" page were very clear and easy to follow. I got caught up on the last step 8/8 on the "Getting Started" page because I didn't realize you had to use the Node command console to enter the npm start command, so I attempted to enter it into Visual Studio, which gave me error results. I then attempted to enter npm install into Visual Studio, which was also rejected. I eventually figured out that you needed to use Node, and from there everything was fine.

The other thing I had a bit of an issue with, which caused me to have to go back and re-submit my request was that for some reason, the first time I tried to go to http://localhost:4200/app/contributors, it wouldn't load, so I was unable to see the changes I had made and it ended up that in the experience column, it looked like I had 2017+ years of experience! The following day, when I looked at it, I realized my error and had to go back to correct it. I learned not to rush my requests through and to check carefully before submitting.

**Comment by coni2k** [comment]
Hi @nakanoer,

Thank you so much for your feedback, it is the most detailed reply I got so far! Appreciated.

Now I'm looking at the instructions; I will add more details about "npm install" part to make it more clear.

I will also re-install the app from scratch to see whether there is any issue with "contributors" page.

For the rest, I'm glad to hear that it went smooth.

I develop applications with ASP.NET & Angular stack. If you have any questions about these technologies, I'd be happy to help.

Recently I started developing another version of Wealth, that is called Backbone, an online public API. It's again very experimental and on a very early stage, but if you can't find anything else, you are welcome to contribute to that one, just send me message.
http://backbone.forcrowd.org
https://github.com/forCrowd/Backbone

Open source & programming journey is long and exciting. Hopefully you can find interesting projects that will let you grow and keep enjoying it.

Thanks again!
